apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: demo
  labels:
    impactgate.io/managed: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
        impactgate.io/managed: "true"
    spec:
      containers:
        - name: payments
          image: nginx:1.25
